title: Mi Sitio
description: Este es mi sitio con Jekyll desde GitHub
theme: minima
title: Mi Sitio Jekyll
theme: minima

collections:
  proyectos:
    output: true
theme: minima
title: Mi Sitio Jekyll

collections:
  proyectos:
    output: true

# Navegación
header_pages:
  - index.md
  - about.md
  - contact.md
  - proyectos.md
